# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ButtonTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'NMButton', :path => '../'  

  # Pods for ButtonTest

  target 'ButtonTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ButtonTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
